name: Build Course Service

on:
  push:
    paths:
      - "course-service/**"
  workflow_dispatch:

jobs:
  build-course:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push course-service image
        uses: docker/build-push-action@v6
        with:
          context: ./course-service
          file: ./course-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/course-service:latest
            ${{ secrets.DOCKER_USERNAME }}/course-service:${{ github.run_number }}
